<?php

namespace Database\Seeders;

use App\Models\GameRole;
use Illuminate\Database\Seeder;

class GameRoleSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            ['name' => 'Witchwork Staff', 'category' => 'Tank', 'icon' => "Elder's Witchwork Staff"],

            ['name' => '1h Mace', 'category' => 'Tank', 'icon' => "Elder's Mace"],
            ['name' => 'Heavy Mace', 'category' => 'Tank', 'icon' => "Elder's Heavy Mace"],
            ['name' => 'Oathkeeper', 'category' => 'Tank', 'icon' => "Elder's Oathkeeper"],
            ['name' => 'Bedrock Mace', 'category' => 'Tank', 'icon' => "Elder's Bedrock Mace"],
            ['name' => 'Morning Star', 'category' => 'Tank', 'icon' => "Elder's Morning Star"],
            ['name' => 'Incubus Mace', 'category' => 'Tank', 'icon' => "Elder's Incubus Mace"],
            ['name' => 'Camlann Mace', 'category' => 'Tank', 'icon' => "Elder's Camlann Mace"],
            ['name' => 'Dreadstorm Monarch', 'category' => 'Tank', 'icon' => "Elder's Dreadstorm Monarch"],
            ['name' => 'Grovekeeper', 'category' => 'Tank', 'icon' => "Elder's Grovekeeper"],
            ['name' => '1h Hammer', 'category' => 'Tank', 'icon' => "Elder's Hammer"],
            ['name' => 'Polehammer', 'category' => 'Tank', 'icon' => "Elder's Polehammer"],
            ['name' => 'Great Hammer', 'category' => 'Tank', 'icon' => "Elder's Great Hammer"],
            ['name' => 'Hand of Justice', 'category' => 'Tank', 'icon' => "Elder's Hand of Justice"],
            ['name' => 'Truebolt Hammmer', 'category' => 'Tank', 'icon' => "Elder's Truebolt Hammmer"],
            ['name' => 'Grailseeker', 'category' => 'Tank', 'icon' => "Elder's Grailseeker"],
            ['name' => 'Black Monk Stave', 'category' => 'Tank', 'icon' => "Elder's Black Monk Stave"],
            ['name' => 'Soulscythe Combat', 'category' => 'Tank', 'icon' => "Elder's Soulscythe Combat"],
            ['name' => 'Staff of Balance', 'category' => 'Tank', 'icon' => "Elder's Staff of Balance"],
            ['name' => 'Earthrune Staff', 'category' => 'Tank', 'icon' => "Elder's Earthrune Staff"],
            ['name' => 'Primal Staff', 'category' => 'Tank', 'icon' => "Elder's Primal Staff"],
            ['name' => 'Stillgaze Staff', 'category' => 'Tank', 'icon' => "Elder's Stillgaze Staff"],
            ['name' => 'Great Arcane', 'category' => 'Tank', 'icon' => "Elder's Great Arcane"],
            ['name' => '1h Arcane', 'category' => 'Tank', 'icon' => "Elder's Arcane Staff"],
            ['name' => 'Tombhammer', 'category' => 'Tank', 'icon' => "Elder's Tombhammer"],
            ['name' => 'Forge Hammers', 'category' => 'Tank', 'icon' => "Elder's Forge Hammers"],

            ['name' => 'Exalted Staff', 'category' => 'Healer', 'icon' => "Elder's Exalted Staff"],
            ['name' => 'Redemption Staff', 'category' => 'Healer', 'icon' => "Elder's Redemption Staff"],
            ['name' => 'Lifetouch Staff', 'category' => 'Healer', 'icon' => "Elder's Lifetouch Staff"],
            ['name' => 'Divine Staff', 'category' => 'Healer', 'icon' => "Elder's Divine Staff"],
            ['name' => 'Great Holy Staff', 'category' => 'Healer', 'icon' => "Elder's Great Holy Staff"],
            ['name' => 'Holy Staff', 'category' => 'Healer', 'icon' => "Elder's Holy Staff"],
            ['name' => 'Hallowfall', 'category' => 'Healer', 'icon' => "Elder's Hallowfall"],
            ['name' => 'Fallen Staff', 'category' => 'Healer', 'icon' => "Elder's Fallen Staff"],

            ['name' => 'Forgebark Staff', 'category' => 'Healer', 'icon' => "Elder's Forgebark Staff"],
            ['name' => 'Ironroot Staff', 'category' => 'Healer', 'icon' => "Elder's Ironroot Staff"],
            ['name' => 'Rampant Staff', 'category' => 'Healer', 'icon' => "Elder's Rampant Staff"],
            ['name' => 'Druidic Staff', 'category' => 'Healer', 'icon' => "Elder's Druidic Staff"],
            ['name' => 'Great Nature Staff', 'category' => 'Healer', 'icon' => "Elder's Great Nature Staff"],
            ['name' => 'Wild Staff', 'category' => 'Healer', 'icon' => "Elder's Wild Staff"],
            ['name' => 'Blight Staff', 'category' => 'Healer', 'icon' => "Elder's Blight Staff"],
            ['name' => 'Nature Staff', 'category' => 'Healer', 'icon' => "Elder's Nature Staff"],

            ['name' => 'Locus', 'category' => 'Support', 'icon' => "Elder's Malevolent Locus"],
            ['name' => 'Enigmatic Staff', 'category' => 'Support', 'icon' => "Elder's Enigmatic Staff"],
            ['name' => 'Occult Staff', 'category' => 'Support', 'icon' => "Elder's Occult Staff"],
            ['name' => 'Evensong', 'category' => 'Support', 'icon' => "Elder's Evensong"],
            ['name' => 'Damnation Staff', 'category' => 'Support', 'icon' => "Elder's Damnation Staff"],
            ['name' => 'Lifecurse Staff', 'category' => 'Support', 'icon' => "Elder's Lifecurse Staff"],
            ['name' => 'Shadowcaller', 'category' => 'Support', 'icon' => "Elder's Shadowcaller"],
            ['name' => 'Rotcaller Staff', 'category' => 'Support', 'icon' => "Elder's Rotcaller Staff"],
            ['name' => 'Icicle Staff', 'category' => 'Support', 'icon' => "Elder's Icicle Staff"],
            ['name' => 'Rootbound Staff', 'category' => 'Support', 'icon' => "Elder's Rootbound Staff"],
            ['name' => 'Ironclad Staff', 'category' => 'Support', 'icon' => "Elder's Ironclad Staff"],
            ['name' => 'Double Bladed Staff', 'category' => 'Support', 'icon' => "Elder's Double Bladed Staff"],
            ['name' => 'Hoarfrost Staff', 'category' => 'Support', 'icon' => "Elder's Hoarfrost Staff"],

            ['name' => 'Carving Sword', 'category' => 'DPS', 'icon' => "Elder's Carving Sword"],
            ['name' => 'Flamewalker Staff', 'category' => 'DPS', 'icon' => "Elder's Flamewalker Staff"],
            ['name' => 'Dawnsong', 'category' => 'DPS', 'icon' => "Elder's Dawnsong"],
            ['name' => 'Blazing Staff', 'category' => 'DPS', 'icon' => "Elder's Blazing Staff"],
            ['name' => 'Brimstone Staff', 'category' => 'DPS', 'icon' => "Elder's Brimstone Staff"],
            ['name' => 'Wildfire Staff', 'category' => 'DPS', 'icon' => "Elder's Wildfire Staff"],
            ['name' => 'Infernal Staff', 'category' => 'DPS', 'icon' => "Elder's Infernal Staff"],
            ['name' => 'Great Fire Staff', 'category' => 'DPS', 'icon' => "Elder's Great Fire Staff"],
            ['name' => 'Fire Staff', 'category' => 'DPS', 'icon' => "Elder's Fire Staff"],
            ['name' => 'Lightcaller', 'category' => 'DPS', 'icon' => "Elder's Lightcaller"],
            ['name' => 'Astral Staff', 'category' => 'DPS', 'icon' => "Elder's Astral Staff"],
            ['name' => 'Chillhowl', 'category' => 'DPS', 'icon' => "Elder's Chillhowl"],
            ['name' => 'Arctic Staff', 'category' => 'DPS', 'icon' => "Elder's Arctic Staff"],
            ['name' => 'Permafrost Prism', 'category' => 'DPS', 'icon' => "Elder's Permafrost Prism"],
            ['name' => 'Glacial Staff', 'category' => 'DPS', 'icon' => "Elder's Glacial Staff"],

            ['name' => 'Phantom Twinblade', 'category' => 'DPS', 'icon' => "Elder's Phantom Twinblade"],
            ['name' => 'Quarterstaff', 'category' => 'DPS', 'icon' => "Elder's Quarterstaff"],
            ['name' => 'Spirit Hunter', 'category' => 'DPS', 'icon' => "Elder's Spirit Hunter"],
            ['name' => 'Rift Glaive', 'category' => 'DPS', 'icon' => "Elder's Rift Glaive"],
            ['name' => 'Daybreaker', 'category' => 'DPS', 'icon' => "Elder's Daybreaker"],

            ['name' => 'Twin Slayers', 'category' => 'DPS', 'icon' => "Elder's Twin Slayers"],
            ['name' => 'Bridled Fury', 'category' => 'DPS', 'icon' => "Elder's Bridled Fury"],
            ['name' => 'Demonfang', 'category' => 'DPS', 'icon' => "Elder's Demonfang"],
            ['name' => 'Bloodletter', 'category' => 'DPS', 'icon' => "Elder's Bloodletter"],

            ['name' => 'Cursed Skull', 'category' => 'DPS', 'icon' => "Elder's Cursed Skull"],
            ['name' => 'Demonic Staff', 'category' => 'DPS', 'icon' => "Elder's Demonic Staff"],
            ['name' => 'Great Cursed Staff', 'category' => 'DPS', 'icon' => "Elder's Great Cursed Staff"],
            ['name' => 'Cursed Staff', 'category' => 'DPS', 'icon' => "Elder's Cursed Staff"],

            ['name' => 'Realmbreaker', 'category' => 'DPS', 'icon' => "Elder's Realmbreaker"],
            ['name' => 'Kingmaker', 'category' => 'DPS', 'icon' => "Elder's Kingmaker"],
            ['name' => 'Clarent Blade', 'category' => 'DPS', 'icon' => "Elder's Clarent Blade"],
            ['name' => 'Galatine Pair', 'category' => 'DPS', 'icon' => "Elder's Galatine Pair"],
            ['name' => 'Infinity Blade', 'category' => 'DPS', 'icon' => "Elder's Infinity Blade"],

            ['name' => 'Longbow', 'category' => 'DPS', 'icon' => "Elder's Longbow"],
            ['name' => 'Mistpiercer', 'category' => 'DPS', 'icon' => "Elder's Mistpiercer"],
            ['name' => 'Bow of Badon', 'category' => 'DPS', 'icon' => "Elder's Bow of Badon"],
            ['name' => 'Wailing Bow', 'category' => 'DPS', 'icon' => "Elder's Wailing Bow"],

            ['name' => 'Weeping Repeater', 'category' => 'DPS', 'icon' => "Elder's Weeping Repeater"],
            ['name' => 'Siegebow', 'category' => 'DPS', 'icon' => "Elder's Siegebow"],
            ['name' => 'Energy Shaper', 'category' => 'DPS', 'icon' => "Elder's Energy Shaper"],
            ['name' => 'Arctic Blasters', 'category' => 'DPS', 'icon' => "Elder's Arctic Blasters"],

            ['name' => 'Battle Bracers', 'category' => 'DPS', 'icon' => "Elder's Battle Bracers"],
            ['name' => 'Spiked Gauntlets', 'category' => 'DPS', 'icon' => "Elder's Spiked Gauntlets"],
            ['name' => 'Ursine Maulers', 'category' => 'DPS', 'icon' => "Elder's Ursine Maulers"],
            ['name' => 'Hellfire Hands', 'category' => 'DPS', 'icon' => "Elder's Hellfire Hands"],
            ['name' => 'Ravenstrike Cestus', 'category' => 'DPS', 'icon' => "Elder's Ravenstrike Cestus"],
            ['name' => 'Fist of Avalon', 'category' => 'DPS', 'icon' => "Elder's Fist of Avalon"],
            ['name' => 'Forcepulse Bracers', 'category' => 'DPS', 'icon' => "Elder's Forcepulse Bracers"],

            ['name' => 'Greataxe', 'category' => 'DPS', 'icon' => "Elder's Greataxe"],
            ['name' => 'Hallberd', 'category' => 'DPS', 'icon' => "Elder's Hallberd"],
            ['name' => 'Carrioncaller', 'category' => 'DPS', 'icon' => "Elder's Carrioncaller"],
            ['name' => 'Infernal Scyhte', 'category' => 'DPS', 'icon' => "Elder's Infernal Scyhte"],
            ['name' => 'Bear Paws', 'category' => 'DPS', 'icon' => "Elder's Bear Paws"],
            ['name' => 'Crystal Reaper', 'category' => 'DPS', 'icon' => "Elder's Crystal Reaper"],

            ['name' => 'Great Frost Staff', 'category' => 'DPS', 'icon' => "Elder's Great Frost Staff"],
            ['name' => 'Frost Staff', 'category' => 'DPS', 'icon' => "Elder's Frost Staff"],

            ['name' => 'Prowling Staff', 'category' => 'DPS', 'icon' => "Elder's Prowling Staff"],
            ['name' => 'Hellspawn Staff', 'category' => 'DPS', 'icon' => "Elder's Hellspawn Staff"],
            ['name' => 'Bloodmoon Staff', 'category' => 'DPS', 'icon' => "Elder's Bloodmoon Staff"],

            ['name' => 'Broadsword', 'category' => 'DPS', 'icon' => "Elder's Broadsword"],
            ['name' => 'Claymore', 'category' => 'DPS', 'icon' => "Elder's Claymore"],
            ['name' => 'Dual Sword', 'category' => 'DPS', 'icon' => "Elder's Dual Sword"],

            ['name' => 'Battleaxe', 'category' => 'DPS', 'icon' => "Elder's Battleaxe"],
            ['name' => 'Brawler Gloves', 'category' => 'DPS', 'icon' => "Elder's Brawler Gloves"],
            ['name' => 'Boltcasters', 'category' => 'DPS', 'icon' => "Elder's Boltcasters"],

            ['name' => 'Light Crossbow', 'category' => 'DPS', 'icon' => "Elder's Light Crossbow"],
            ['name' => 'Heavy Crossbow', 'category' => 'DPS', 'icon' => "Elder's Heavy Crossbow"],
            ['name' => 'Crossbow', 'category' => 'DPS', 'icon' => "Elder's Crossbow"],

            ['name' => 'Whispering Bow', 'category' => 'DPS', 'icon' => "Elder's Whispering Bow"],
            ['name' => 'Warbow', 'category' => 'DPS', 'icon' => "Elder's Warbow"],
            ['name' => 'Bow', 'category' => 'DPS', 'icon' => "Elder's Bow"],
            ['name' => 'Dagger Pair', 'category' => 'DPS', 'icon' => "Elder's Dagger Pair"],
            ['name' => 'Dagger', 'category' => 'DPS', 'icon' => "Elder's Dagger"],
            ['name' => 'Claws', 'category' => 'DPS', 'icon' => "Elder's Claws"],

            ['name' => 'Deathgivers', 'category' => 'DPS', 'icon' => "Elder's Deathgivers"],
            ['name' => 'Pike', 'category' => 'DPS', 'icon' => "Elder's Pike"],
            ['name' => 'Spear', 'category' => 'DPS', 'icon' => "Elder's Spear"],
            ['name' => 'Trinity Spear', 'category' => 'DPS', 'icon' => "Elder's Trinity Spear"],
            ['name' => 'Heron Spear', 'category' => 'DPS', 'icon' => "Elder's Heron Spear"],
            ['name' => 'Glaive', 'category' => 'DPS', 'icon' => "Elder's Glaive"],


            ['name' => 'Ancient Ent' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Flame Basilisk' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Venom Basilisk' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Roving Bastion' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Battle Eagle' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Battle Rhino' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Behemoth' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Goliath Horseeater' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Siege Ballista' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Juggernaut' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Tower Chariot' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Phalanx Beetle' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Colossus Beetle' , 'category' => 'Battle Mount' ] ,
            ['name' => 'Command Mammoth' , 'category' => 'Battle Mount' ] ,

            ['name' => 'Soldier Helmet', 'category' => 'Plate Armor Helmet', 'icon' => "Elder's Soldier Helmet"],
            ['name' => 'Knight Helmet', 'category' => 'Plate Armor Helmet', 'icon' => "Elder's Knight Helmet"],
            ['name' => 'Guardian Helmet', 'category' => 'Plate Armor Helmet', 'icon' => "Elder's Guardian Helmet"],
            ['name' => 'Royal Helmet', 'category' => 'Plate Armor Helmet', 'icon' => "Elder's Royal Helmet"],
            ['name' => 'Judicator Helmet', 'category' => 'Plate Armor Helmet', 'icon' => "Elder's Judicator Helmet"],
            ['name' => 'Graveguard Helmet', 'category' => 'Plate Armor Helmet', 'icon' => "Elder's Graveguard Helmet"],
            ['name' => 'Demon Helmet', 'category' => 'Plate Armor Helmet', 'icon' => "Elder's Demon Helmet"],
            ['name' => 'Helmet of Valor', 'category' => 'Plate Armor Helmet', 'icon' => "Elder's Helmet of Valor"],
            ['name' => 'Duskweaver Helmet', 'category' => 'Plate Armor Helmet', 'icon' => "Elder's Duskweaver Helmet"],

            ['name' => 'Soldier Armor', 'category' => 'Plate Armor Chest', 'icon' => "Elder's Soldier Armor"],
            ['name' => 'Knight Armor', 'category' => 'Plate Armor Chest', 'icon' => "Elder's Knight Armor"],
            ['name' => 'Guardian Armor', 'category' => 'Plate Armor Chest', 'icon' => "Elder's Guardian Armor"],
            ['name' => 'Royal Armor', 'category' => 'Plate Armor Chest', 'icon' => "Elder's Royal Armor"],
            ['name' => 'Judicator Armor', 'category' => 'Plate Armor Chest', 'icon' => "Elder's Judicator Armor"],
            ['name' => 'Graveguard Armor', 'category' => 'Plate Armor Chest', 'icon' => "Elder's Graveguard Armor"],
            ['name' => 'Demon Armor', 'category' => 'Plate Armor Chest', 'icon' => "Elder's Demon Armor"],
            ['name' => 'Armor of Valor', 'category' => 'Plate Armor Chest', 'icon' => "Elder's Armor of Valor"],
            ['name' => 'Duskweaver Armor', 'category' => 'Plate Armor Chest', 'icon' => "Elder's Duskweaver Armor"],

            ['name' => 'Soldier Boots', 'category' => 'Plate Armor Shoes', 'icon' => "Elder's Soldier Boots"],
            ['name' => 'Knight Boots', 'category' => 'Plate Armor Shoes', 'icon' => "Elder's Knight Boots"],
            ['name' => 'Guardian Boots', 'category' => 'Plate Armor Shoes', 'icon' => "Elder's Guardian Boots"],
            ['name' => 'Royal Boots', 'category' => 'Plate Armor Shoes', 'icon' => "Elder's Royal Boots"],
            ['name' => 'Judicator Boots', 'category' => 'Plate Armor Shoes', 'icon' => "Elder's Judicator Boots"],
            ['name' => 'Graveguard Boots', 'category' => 'Plate Armor Shoes', 'icon' => "Elder's Graveguard Boots"],
            ['name' => 'Demon Boots', 'category' => 'Plate Armor Shoes', 'icon' => "Elder's Demon Boots"],
            ['name' => 'Boots of Valor', 'category' => 'Plate Armor Shoes', 'icon' => "Elder's Boots of Valor"],
            ['name' => 'Duskweaver Boots', 'category' => 'Plate Armor Shoes', 'icon' => "Elder's Duskweaver Boots"],

            ['name' => 'Mercenary Hood', 'category' => 'Leather Armor Helmet', 'icon' => "Elder's Mercenary Hood"],
            ['name' => 'Hunter Hood', 'category' => 'Leather Armor Helmet', 'icon' => "Elder's Hunter Hood"],
            ['name' => 'Assassin Hood', 'category' => 'Leather Armor Helmet', 'icon' => "Elder's Assassin Hood"],
            ['name' => 'Royal Hood', 'category' => 'Leather Armor Helmet', 'icon' => "Elder's Royal Hood"],
            ['name' => 'Stalker Hood', 'category' => 'Leather Armor Helmet', 'icon' => "Elder's Stalker Hood"],
            ['name' => 'Hellion Hood', 'category' => 'Leather Armor Helmet', 'icon' => "Elder's Hellion Hood"],
            ['name' => 'Specter Hood', 'category' => 'Leather Armor Helmet', 'icon' => "Elder's Specter Hood"],
            ['name' => 'Mistwalker Hood', 'category' => 'Leather Armor Helmet', 'icon' => "Elder's Mistwalker Hood"],
            ['name' => 'Hood of Tenacity', 'category' => 'Leather Armor Helmet', 'icon' => "Elder's Hood of Tenacity"],

            ['name' => 'Mercenary Jacket', 'category' => 'Leather Armor Chest', 'icon' => "Elder's Mercenary Jacket"],
            ['name' => 'Hunter Jacket', 'category' => 'Leather Armor Chest', 'icon' => "Elder's Hunter Jacket"],
            ['name' => 'Assassin Jacket', 'category' => 'Leather Armor Chest', 'icon' => "Elder's Assassin Jacket"],
            ['name' => 'Royal Jacket', 'category' => 'Leather Armor Chest', 'icon' => "Elder's Royal Jacket"],
            ['name' => 'Stalker Jacket', 'category' => 'Leather Armor Chest', 'icon' => "Elder's Stalker Jacket"],
            ['name' => 'Hellion Jacket', 'category' => 'Leather Armor Chest', 'icon' => "Elder's Hellion Jacket"],
            ['name' => 'Specter Jacket', 'category' => 'Leather Armor Chest', 'icon' => "Elder's Specter Jacket"],
            ['name' => 'Jacket of Tenacity', 'category' => 'Leather Armor Chest', 'icon' => "Elder's Jacket of Tenacity"],
            ['name' => 'Mistwalker Jacket', 'category' => 'Leather Armor Chest', 'icon' => "Elder's Mistwalker Jacket"],

            ['name' => 'Mercenary Shoes', 'category' => 'Leather Armor Shoes', 'icon' => "Elder's Mercenary Shoes"],
            ['name' => 'Hunter Shoes', 'category' => 'Leather Armor Shoes', 'icon' => "Elder's Hunter Shoes"],
            ['name' => 'Assassin Shoes', 'category' => 'Leather Armor Shoes', 'icon' => "Elder's Assassin Shoes"],
            ['name' => 'Royal Shoes', 'category' => 'Leather Armor Shoes', 'icon' => "Elder's Royal Shoes"],
            ['name' => 'Stalker Shoes', 'category' => 'Leather Armor Shoes', 'icon' => "Elder's Stalker Shoes"],
            ['name' => 'Hellion Shoes', 'category' => 'Leather Armor Shoes', 'icon' => "Elder's Hellion Shoes"],
            ['name' => 'Specter Shoes', 'category' => 'Leather Armor Shoes', 'icon' => "Elder's Specter Shoes"],
            ['name' => 'Shoes of Tenacity', 'category' => 'Leather Armor Shoes', 'icon' => "Elder's Shoes of Tenacity"],
            ['name' => 'Mistwalker Shoes', 'category' => 'Leather Armor Shoes', 'icon' => "Elder's Mistwalker Shoes"],

            ['name' => 'Mage Cowl', 'category' => 'Cloth Armor Helmet', 'icon' => "Elder's Mage Cowl"],
            ['name' => 'Cleric Cowl', 'category' => 'Cloth Armor Helmet', 'icon' => "Elder's Cleric Cowl"],
            ['name' => 'Scholar Cowl', 'category' => 'Cloth Armor Helmet', 'icon' => "Elder's Scholar Cowl"],
            ['name' => 'Royal Cowl', 'category' => 'Cloth Armor Helmet', 'icon' => "Elder's Royal Cowl"],
            ['name' => 'Fiend Cowl', 'category' => 'Cloth Armor Helmet', 'icon' => "Elder's Fiend Cowl"],
            ['name' => 'Cultist Cowl', 'category' => 'Cloth Armor Helmet', 'icon' => "Elder's Cultist Cowl"],
            ['name' => 'Druid Cowl', 'category' => 'Cloth Armor Helmet', 'icon' => "Elder's Druid Cowl"],
            ['name' => 'Cowl of Purity', 'category' => 'Cloth Armor Helmet', 'icon' => "Elder's Cowl of Purity"],
            ['name' => 'Feyscale Hat', 'category' => 'Cloth Armor Helmet', 'icon' => "Elder's Feyscale Hat"],

            ['name' => 'Mage Robe', 'category' => 'Cloth Armor Chest', 'icon' => "Elder's Mage Robe"],
            ['name' => 'Cleric Robe', 'category' => 'Cloth Armor Chest', 'icon' => "Elder's Cleric Robe"],
            ['name' => 'Scholar Robe', 'category' => 'Cloth Armor Chest', 'icon' => "Elder's Scholar Robe"],
            ['name' => 'Royal Robe', 'category' => 'Cloth Armor Chest', 'icon' => "Elder's Royal Robe"],
            ['name' => 'Fiend Robe', 'category' => 'Cloth Armor Chest', 'icon' => "Elder's Fiend Robe"],
            ['name' => 'Cultist Robe', 'category' => 'Cloth Armor Chest', 'icon' => "Elder's Cultist Robe"],
            ['name' => 'Druid Robe', 'category' => 'Cloth Armor Chest', 'icon' => "Elder's Druid Robe"],
            ['name' => 'Robe of Purity', 'category' => 'Cloth Armor Chest', 'icon' => "Elder's Robe of Purity"],
            ['name' => 'Feyscale Robe', 'category' => 'Cloth Armor Chest', 'icon' => "Elder's Feyscale Robe"],

            ['name' => 'Mage Sandals', 'category' => 'Cloth Armor Shoes', 'icon' => "Elder's Mage Sandals"],
            ['name' => 'Cleric Sandals', 'category' => 'Cloth Armor Shoes', 'icon' => "Elder's Cleric Sandals"],
            ['name' => 'Scholar Sandals', 'category' => 'Cloth Armor Shoes', 'icon' => "Elder's Scholar Sandals"],
            ['name' => 'Royal Sandals', 'category' => 'Cloth Armor Shoes', 'icon' => "Elder's Royal Sandals"],
            ['name' => 'Fiend Sandals', 'category' => 'Cloth Armor Shoes', 'icon' => "Elder's Fiend Sandals"],
            ['name' => 'Cultist Sandals', 'category' => 'Cloth Armor Shoes', 'icon' => "Elder's Cultist Sandals"],
            ['name' => 'Druid Sandals', 'category' => 'Cloth Armor Shoes', 'icon' => "Elder's Druid Sandals"],
            ['name' => 'Feyscale Sandals', 'category' => 'Cloth Armor Shoes', 'icon' => "Elder's Feyscale Sandals"],
            ['name' => 'Sandals of Purity', 'category' => 'Cloth Armor Shoes', 'icon' => "Elder's Sandals of Purity"],

            ['name' => 'Shield', 'category' => 'Shield', 'icon' => "Elder's Shield"],
            ['name' => 'Sarcophagus', 'category' => 'Shield', 'icon' => "Elder's Sarcophagus"],
            ['name' => 'Caitiff Shield', 'category' => 'Shield', 'icon' => "Elder's Caitiff Shield"],
            ['name' => 'Facebreaker', 'category' => 'Shield', 'icon' => "Elder's Facebreaker"],
            ['name' => 'Astral Aegis', 'category' => 'Shield', 'icon' => "Elder's Astral Aegis"],
            ['name' => 'Unbreakable Ward', 'category' => 'Shield', 'icon' => "Elder's Unbreakable Ward"],

            ['name' => 'Torch', 'category' => 'Offhand', 'icon' => "Elder's Torch"],
            ['name' => 'Mistcaller', 'category' => 'Offhand', 'icon' => "Elder's Mistcaller"],
            ['name' => 'Leering Cane', 'category' => 'Offhand', 'icon' => "Elder's Leering Cane"],
            ['name' => 'Cryptcandle', 'category' => 'Offhand', 'icon' => "Elder's Cryptcandle"],
            ['name' => 'Sacred Scepter', 'category' => 'Offhand', 'icon' => "Elder's Sacred Scepter"],
            ['name' => 'Blueflame Torch', 'category' => 'Offhand', 'icon' => "Elder's Blueflame Torch"],
            ['name' => 'Tome of Spells', 'category' => 'Offhand', 'icon' => "Elder's Tome of Spells"],
            ['name' => 'Eye of Secrets', 'category' => 'Offhand', 'icon' => "Elder's Eye of Secrets"],
            ['name' => 'Taproot', 'category' => 'Offhand', 'icon' => "Elder's Taproot"],
            ['name' => 'Celestial Censer', 'category' => 'Offhand', 'icon' => "Elder's Celestial Censer"],
            ['name' => 'Timelocked Grimoire', 'category' => 'Offhand', 'icon' => "Elder's Timelocked Grimoire"],

            ['name' => 'Martlock Cape' , 'category' => 'Cape' , 'icon' => "Elder's Martlock Cape"],
            ['name' => 'Smuggler Cape' , 'category' => 'Cape' , 'icon' => "Elder's Smuggler Cape"],
            ['name' => 'Brecilien Cape' , 'category' => 'Cape' , 'icon' => "Elder's Brecilien Cape"],
            ['name' => 'Lymhurst Cape' , 'category' => 'Cape' , 'icon' => "Elder's Lymhurst Cape"],
            ['name' => 'Morgana Cape' , 'category' => 'Cape' , 'icon' => "Elder's Morgana Cape"],
            ['name' => 'Undead Cape' , 'category' => 'Cape' , 'icon' => "Elder's Undead Cape"],
            ['name' => 'Avalonian Cape' , 'category' => 'Cape' , 'icon' => "Elder's Avalonian Cape"],
            ['name' => 'Bridgewatch Cape' , 'category' => 'Cape' , 'icon' => "Elder's Bridgewatch Cape"],
            ['name' => 'Forst Sterling Cape' , 'category' => 'Cape' , 'icon' => "Elder's Forst Sterling Cape"],
            ['name' => 'Demon Cape' , 'category' => 'Cape' , 'icon' => "Elder's Demon Cape"],
            ['name' => 'Thetfort Cape' , 'category' => 'Cape' , 'icon' => "Elder's Thetfort Cape"],
            ['name' => 'Carleon Cape' , 'category' => 'Cape' , 'icon' => "Elder's Carleon Cape"],
            ['name' => 'Keeper Cape' , 'category' => 'Cape' , 'icon' => "Elder's Keeper Cape"],
            ['name' => 'Heretic Cape' , 'category' => 'Cape' , 'icon' => "Elder's Heretic Cape"],

            ['name' => 'Gigantify Potion' , 'category' => 'Potion' , 'icon' => "Major Gigantify Potion"],
            ['name' => 'Resistance Potion' , 'category' => 'Potion' , 'icon' => "Major Resistance Potion"],
            ['name' => 'Cleansing Potion' , 'category' => 'Potion' , 'icon' => "Major Cleansing Potion"],

            ['name' => 'Pork Omelette' , 'category' => 'Food' , 'icon' => "Pork Omelette"],
            ['name' => 'Avalonian Pork Omelette' , 'category' => 'Food' , 'icon' => "Avalonian Pork Omelette"],
            ['name' => 'Dusthole Crab Omelette' , 'category' => 'Food' , 'icon' => "Dusthole Crab Omelette"],
            ['name' => 'Beef Stew' , 'category' => 'Food' , 'icon' => "Beef Stew"],
            ['name' => 'Avalonian Beef Stew' , 'category' => 'Food' , 'icon' => "Avalonian Beef Stew"],
            ['name' => 'Beef Sandwich' , 'category' => 'Food' , 'icon' => "Beef Sandwich"],
            ['name' => 'Avalonian Beef Sandwich' , 'category' => 'Food' , 'icon' => "Avalonian Beef Sandwich"],

        ];

        foreach ($roles as $role) {
            GameRole::create($role);
        }
    }
    }
