<?php

namespace Database\Seeders;

use App\Models\GameRole;
use Illuminate\Database\Seeder;

class GameRoleSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            //Tanks
            ['name' => '1h Mace' , 'category' => 'Tank'] ,
            ['name' => 'Heavy Mace' , 'category' => 'Tank'] ,
            ['name' => 'Oathkeeper' , 'category' => 'Tank'] ,
            ['name' => 'Bedrock Mace' , 'category' => 'Tank'] ,
            ['name' => 'Morning Star' , 'category' => 'Tank'] ,
            ['name' => 'Incubus Mace' , 'category' => 'Tank'] ,
            ['name' => 'Camlann Mace' , 'category' => 'Tank'] ,
            ['name' => 'Dreadstorm Monarch' , 'category' => 'Tank'] ,
            ['name' => 'Grovekeeper' , 'category' => 'Tank'] ,
            ['name' => '1h Hammer' , 'category' => 'Tank'] ,
            ['name' => 'Polehammer' , 'category' => 'Tank'] ,
            ['name' => 'Great Hammer' , 'category' => 'Tank'] ,
            ['name' => 'Hand of Justice' , 'category' => 'Tank'] ,
            ['name' => 'Truebolt Hammmer' , 'category' => 'Tank'] ,
            ['name' => 'Grailseeker' , 'category' => 'Tank'] ,
            ['name' => 'Black Monk Stave' , 'category' => 'Tank'] ,
            ['name' => 'Soulscythe Combat' , 'category' => 'Tank'] ,
            ['name' => 'Staff of Balance' , 'category' => 'Tank'] ,
            ['name' => 'Earthrune Staff' , 'category' => 'Tank'] ,
            ['name' => 'Primal Staff' , 'category' => 'Tank'] ,
            ['name' => 'Stillgaze Staff' , 'category' => 'Tank'] ,
            ['name' => 'Great Arcane' , 'category' => 'Tank'] ,
            ['name' => '1h Arcane' , 'category' => 'Tank'] ,

            //Healers
            ['name' => 'Exalted Staff' , 'category' => 'Healer'] ,
            ['name' => 'Redemption Staff' , 'category' => 'Healer'] ,
            ['name' => 'Lifetouch Staff' , 'category' => 'Healer'] ,
            ['name' => 'Divine Staff' , 'category' => 'Healer'] ,
            ['name' => 'Great Holy Staff' , 'category' => 'Healer'] ,
            ['name' => 'Holy Staff' , 'category' => 'Healer'] ,
            ['name' => 'Hallowfall' , 'category' => 'Healer'] ,
            ['name' => 'Fallen Staff' , 'category' => 'Healer'] ,
            ['name' => 'Forgebark Staff' , 'category' => 'Healer'] ,
            ['name' => 'Ironroot Staff' , 'category' => 'Healer'] ,
            ['name' => 'Rampant Staff' , 'category' => 'Healer'] ,
            ['name' => 'Druidic Staff' , 'category' => 'Healer'] ,
            ['name' => 'Great Nature Staff' , 'category' => 'Healer'] ,
            ['name' => 'Wild Staff' , 'category' => 'Healer'] ,
            ['name' => 'Blight Staff' , 'category' => 'Healer'] ,
            ['name' => 'Nature Staff' , 'category' => 'Healer'] ,

            //SUPPORTS
            ['name' => 'Locus' , 'category' => 'Support'] ,
            ['name' => 'Enigmatic Staff' , 'category' => 'Support'] ,
            ['name' => 'Occult Staff' , 'category' => 'Support'] ,
            ['name' => 'Evensong' , 'category' => 'Support'] ,
            ['name' => 'Damnation Staff' , 'category' => 'Support'] ,
            ['name' => 'Lifecurse Staff' , 'category' => 'Support'] ,
            ['name' => 'Shadowcaller' , 'category' => 'Support'] ,
            ['name' => 'Rotcaller Staff' , 'category' => 'Support'] ,
            ['name' => 'Icicle Staff' , 'category' => 'Support'] ,
            ['name' => 'Carving Sword', 'category' => 'DPS' ],
            ['name' => 'Rootbound Staff','category' => 'Support'],

            //DPS
            ['name' => 'Flamewalker Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Dawnsong' , 'category' => 'DPS' ] ,
            ['name' => 'Blazing Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Brimstone Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Wildfire Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Infernal Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Great Fire Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Fire Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Lightcaller' , 'category' => 'DPS' ] ,
            ['name' => 'Astral Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Chillhowl' , 'category' => 'DPS' ] ,
            ['name' => 'Arctic Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Permafrost Prism' , 'category' => 'DPS' ] ,
            ['name' => 'Glacial Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Phantom Twinblade' , 'category' => 'DPS' ] ,
            ['name' => 'Spirit Hunter' , 'category' => 'DPS' ] ,
            ['name' => 'Rift Glaive' , 'category' => 'DPS' ] ,
            ['name' => 'Daybreaker' , 'category' => 'DPS' ] ,
            ['name' => 'Twin Slayers' , 'category' => 'DPS' ] ,
            ['name' => 'Bridled Fury' , 'category' => 'DPS' ] ,
            ['name' => 'Demonfang' , 'category' => 'DPS' ] ,
            ['name' => 'Bloodletter' , 'category' => 'DPS' ] ,
            ['name' => 'Cursed Skull' , 'category' => 'DPS' ] ,
            ['name' => 'Realmbreaker' , 'category' => 'DPS' ] ,
            ['name' => 'Kingmaker' , 'category' => 'DPS' ] ,
            ['name' => 'Clarent Blade' , 'category' => 'DPS' ] ,
            ['name' => 'Galatine Pair' , 'category' => 'DPS' ] ,
            ['name' => 'Infinity Blade' , 'category' => 'DPS' ] ,
            ['name' => 'Longbow' , 'category' => 'DPS' ] ,
            ['name' => 'Mistpiercer' , 'category' => 'DPS' ] ,
            ['name' => 'Bow of Badon' , 'category' => 'DPS' ] ,
            ['name' => 'Wailing Bow' , 'category' => 'DPS' ] ,
            ['name' => 'Weeping Repeater' , 'category' => 'DPS' ] ,
            ['name' => 'Siegebow' , 'category' => 'DPS' ] ,
            ['name' => 'Energy Shaper' , 'category' => 'DPS' ] ,
            ['name' => 'Arctic Blasters' , 'category' => 'DPS' ] ,
            ['name' => 'Battle Bracers' , 'category' => 'DPS' ] ,
            ['name' => 'Spiked Gauntlets' , 'category' => 'DPS' ] ,
            ['name' => 'Ursine Maulers' , 'category' => 'DPS' ] ,
            ['name' => 'Hellfire Hands' , 'category' => 'DPS' ] ,
            ['name' => 'Ravenstrike Cestus' , 'category' => 'DPS' ] ,
            ['name' => 'Fist of Avalon' , 'category' => 'DPS' ] ,
            ['name' => 'Forcepulse Bracers' , 'category' => 'DPS' ] ,
            ['name' => 'Greataxe' , 'category' => 'DPS' ] ,
            ['name' => 'Hallberd' , 'category' => 'DPS' ] ,
            ['name' => 'Carrioncaller' , 'category' => 'DPS' ] ,
            ['name' => 'Infernal Scyhte' , 'category' => 'DPS' ] ,
            ['name' => 'Bear Paws' , 'category' => 'DPS' ] ,
            ['name' => 'Crystal Reaper' , 'category' => 'DPS' ] ,
            ['name' => 'Great Frost Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Frost Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Prowling Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Hellspawn Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Bloodmoon Staff' , 'category' => 'DPS' ] ,
            ['name' => 'Broadsword' , 'category' => 'DPS' ] ,
            ['name' => 'Claymore' , 'category' => 'DPS' ] ,
            ['name' => 'Dual Sword' , 'category' => 'DPS' ] ,
            ['name' => 'Battleaxe' , 'category' => 'DPS' ] ,
            ['name' => 'Brawler Gloves' , 'category' => 'DPS' ] ,
            ['name' => 'Boltcasters' , 'category' => 'DPS' ] ,
            ['name' => 'Light Crossbow' , 'category' => 'DPS' ] ,
            ['name' => 'Heavy Crossbow' , 'category' => 'DPS' ] ,
            ['name' => 'Crossbow' , 'category' => 'DPS' ] ,
            ['name' => 'Whispering Bow', 'category' => 'DPS' ] ,
            ['name' => 'Warbow' , 'category' => 'DPS' ] ,
            ['name' => 'Bow' , 'category' => 'DPS' ] ,
            ['name' => 'Dagger Pair', 'category' => 'DPS' ] ,
            ['name' => 'Dagger' , 'category' => 'DPS' ] ,
            ['name' => 'Claws' , 'category' => 'DPS' ] ,
            ['name' => 'Deathgivers', 'category' => 'DPS' ] ,
            ['name' => 'Pike' , 'category' => 'DPS' ] ,
            ['name' => 'Spear' , 'category' => 'DPS' ] ,
            ['name' => 'Trinity Spear', 'category' => 'DPS' ] ,
            ['name' => 'Heron Spear' , 'category' => 'DPS' ] ,
            ['name' => 'Glaive' , 'category' => 'DPS' ] ,
        ];

        foreach ($roles as $role) {
            GameRole::create($role);
        }
    }
    }
